# Test

In [19]:
import torch
net=torch.nn.Linear(2,4)
optim=torch.optim.Adam(net.parameters(),lr=0.001)
loss=torch.nn.CrossEntropyLoss()


In [20]:
def trainBatch(net,x,y,optimizer,lossFunction):
    optim.zero_grad()
    y_hat=net(torch.tensor([[1,2]]).to(torch.float32))
    l=loss(y_hat,y)
    l.backward()
    optim.step()
    pass

In [21]:
list(net.parameters())

[Parameter containing:
 tensor([[-0.1537, -0.4658],
         [ 0.0176, -0.6108],
         [-0.0918, -0.4873],
         [ 0.1385, -0.3450]], requires_grad=True),
 Parameter containing:
 tensor([-0.0649,  0.6815,  0.5312, -0.2131], requires_grad=True)]

In [43]:
trainBatch(net,1,torch.tensor([2]))
list(net.parameters())

[Parameter containing:
 tensor([[-0.1747, -0.4867],
         [-0.0034, -0.6317],
         [-0.0709, -0.4663],
         [ 0.1175, -0.3659]], requires_grad=True),
 Parameter containing:
 tensor([-0.0859,  0.6606,  0.5522, -0.2341], requires_grad=True)]

In [44]:
optimizer=optim

In [ ]:
from torch.utils.data import *

In [ ]:
def trainBatch(net,x,y,optimizer,lossFunction):
    optimizer.zero_grad()
    y_hat=net(x)
    loss=lossFunction(y_hat,y)
    loss.backward()
    optimizer.step()
    return y,y_hat,loss

In [ ]:
def XYSeparateFunion(batchData):
    xBatch=0
    yBatch=0
    return xBatch,yBatch

In [ ]:
def trainOneEpoch(net,dataloader,XYSeparateFunion,optimizer,lossFunction):
    epochY=torch.tensor([])
    epochLoss=torch.tensor([])
    epochYhat=torch.tensor([])
    for i,data in enumerate(dataloader):
        y,y_hat,loss=trainBatch(net,dataloader,optimizer,lossFunction)
        torch
    return loss,y,y_hat

In [3]:
from sklearn.metrics import confusion_matrix
import numpy as np

# 实际和预测标签列表示例
y_true = [0, 1, 0, 2, 1, 0, 2, 2]
y_pred = [0, 1, 1, 2, 1, 0, 1, 2]

# 计算混淆矩阵
cm = confusion_matrix(y_true, y_pred)

# 计算每个类别的数量
class_counts = np.sum(cm, axis=1)

# 打印混淆矩阵和每个类别的数量
print("混淆矩阵：")
print(cm)
print("每个类别的数量：")
print(class_counts)

混淆矩阵：
[[2 1 0]
 [0 2 0]
 [0 1 2]]
每个类别的数量：
[3 2 3]


In [ ]:
def trainEpochs(net,traindataloader,testdataloader,XYSeparateFunion,optimiser,lossFuntion):
    
    pass

In [ ]:
def kFoldTrain(net,K,dataset,optimiser,lossFuntion):
    pass

In [ ]:
def saveTrainLog(graph,trainAccList,testAccList,lossList,trainIndex,testIndex):
    pass

In [ ]:
def analyseDataset(dataset):
    classDict={'classnum','classname','samplesize'}
    return classDict

In [ ]:
def confusionMatrix(y,y_hat):
    
    pass
def drawConfusionMatrix(confusionMatrix):
    pass

## 自动训练器类
1. 输入：net,dataloader 
2. 需要自定义的部分：trainBatch

In [68]:
import torch
a=torch.tensor([1,2,3,4,5])
b=torch.tensor([[1,2,3,4,5]])

In [48]:
list=[]


In [50]:
list.append(a)
list

[tensor([1, 2, 3, 4, 5]), tensor([1, 2, 3, 4, 5])]

In [51]:
torch.tensor(list)

TypeError: only integer tensors of a single element can be converted to an index

In [70]:
concat=torch.tensor([])


In [74]:
concat=torch.concat([concat,b],dim=0)
concat

tensor([[1., 2., 3., 4., 5.],
        [1., 2., 3., 4., 5.],
        [1., 2., 3., 4., 5.],
        [1., 2., 3., 4., 5.]])

- 类方法调用包中的方法是为了方法的分离性，保证方法可以单独被调用，而不是与类绑定的

In [76]:
class ClassfierTrainer():
    def __init__(self,net,epochNum,optimizer,lossFuntion):
        self.Net=net
        self.EpcochNum=epochNum
        self.Optimizer=optimizer
        self.LossFuntion=lossFuntion
        pass

    def __call__(self):
        self.run()
        pass
    
    def SetNet(self):
        pass
    def SetEpochNum(self):
        pass
    def SetDataloader(self):
        pass
    def SplitDataloader(self):
        pass
    def run(self):
        
        pass
    def TrainBatch(self):
        pass
    def TrainOneEpoch(self):
        pass
    def TrainEpochs(self):
        pass
    def Statitics(self):
        pass
    def KflodTrain(self):
        pass
    pass

In [77]:
a=ClassfierTrainer(net,3,optim,torch.nn.L1Loss())

In [81]:
a.Net
a.Optimizer

Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: None
    lr: 0.001
    maximize: False
    weight_decay: 0
)

# project文件测试

In [1]:
import os
import sys
root=os.path.abspath(os.path.join(r"D:\project_meta\NNproject\NNI\notebook\NNITest_0231104.ipynb","../.."))
print(root)
sys.path.append(root)
os.environ["TORCH_HOME"]=r"E:\Data\torch-model"


D:\project_meta\NNproject\NNI


In [2]:
from project.train.classfierTrainer import ClassfierTrainer
from torch import nn,optim
net=nn.Linear(2,3)
optimizer=optim.Adam(net.parameters(),lr=0.001)
lossFuction=nn.CrossEntropyLoss()
CT=ClassfierTrainer(net=net,optimizer=optimizer,lossFuntion=lossFuction,epochNum=3)

In [6]:
class base:
    def __init__(self,a):
        print(a)
class son(base):
    def __init__(self,b):
        super().__init__(b)
    def XYSeparateFunion(fun,data):
        xBatch,yBatch=fun(data)
        return xBatch,yBatch
a='nn'
def xys(data):
    return data[0],data[1]
s=son(a)

nn


In [5]:
def fun(a):
    print(a)
def ff(f):
    f('ss')
ff(fun) 

ss


- 使用逻辑
- 固定内容：trainBatch(),trainOneEpochs(),trainEpochs()
- 不固定的内容：dataloader,net,optimizer,lossfuntcion,dataloader不确定带来的问题就是读dataloader时的不确定
- 解决dataloader带来的不确定性的方法：
  1. 标准化dataset
  2. 引入dataloader读取程序
  3. 每次重写trainBatch/trainOneEpoch
  - 总结：最靠谱的方法时标准化dataset 
  - 可以通过继承dataset类在__getiterm__中分出多个子类
- 写好trainer后，只需要根据需要给训练添加装饰器即可

In [7]:
from project.train.operation import *
from torch import nn
net=nn.Linear(2,3)


In [16]:
torch.randn([1,3])

tensor([[ 0.8845,  0.1390, -1.4317]])

In [28]:
a=[1,3]


[4, 1, 3]


In [34]:
a.insert(0,4)
print(a)

[4, 4, 4, 4, 4, 4, 4, 1, 3]


In [24]:
a

[4, 1, 3]

In [13]:
tuple()

TypeError: 'NoneType' object is not iterable

In [35]:
shape=[1,3]
length=3
shape.insert(0,length)

TestData=torch.randn(shape)
TestData.shape

torch.Size([3, 1, 3])

In [7]:
from torch.utils.data import Dataset
import torch
from typing import Any
class TestDataset(Dataset):
    def __init__(self,shape:list):
        self.TestData=torch.randn(shape)
        self.label=torch.randn([shape[0]])
    def __len__(self):
        return len(self.TestData)
    def __getitem__(self, index) -> Any:
        return self.TestData[index],self.label[index]

In [77]:
testdataset=TestDataset([100,3])


In [67]:
testdataset[0][0],testdataset[0][1]

(tensor([ 0.2200, -0.9177, -1.1106]), tensor(-0.1218))

In [68]:
net=nn.Linear(3,1)
net(testdataset[0][0])

tensor([0.3711], grad_fn=<ViewBackward0>)

In [8]:
from torch.utils.data import *
testdataset=TestDataset([100,1,3])
dataloader=DataLoader(testdataset,batch_size=2)

In [9]:
list(dataloader)

[[tensor([[[ 0.7733,  0.2821, -0.0801]],
  
          [[ 0.3697, -1.0479,  0.0624]]]),
  tensor([0.3575, 0.2307])],
 [tensor([[[ 0.6849,  1.2877,  3.3969]],
  
          [[ 0.7287,  1.9938, -0.6530]]]),
  tensor([0.0223, 0.6444])],
 [tensor([[[-1.4314, -1.8274,  0.5222]],
  
          [[-2.1946, -1.7025,  0.6805]]]),
  tensor([1.6951, 1.1413])],
 [tensor([[[-0.9726, -0.9064, -0.7550]],
  
          [[ 0.2623,  2.0315, -0.6698]]]),
  tensor([-0.0838, -1.7212])],
 [tensor([[[-0.8926,  0.4090,  1.8849]],
  
          [[-1.6250, -0.3731, -0.3072]]]),
  tensor([-1.4775, -0.5087])],
 [tensor([[[ 1.7758, -0.5382, -0.5731]],
  
          [[ 0.4149, -0.7815, -0.6390]]]),
  tensor([ 0.1852, -0.3218])],
 [tensor([[[ 0.0494, -1.1059,  0.0981]],
  
          [[-1.6352, -0.4780,  0.7897]]]),
  tensor([1.0751, 1.7171])],
 [tensor([[[ 0.5188, -1.3945, -0.1816]],
  
          [[ 1.3527, -0.2515,  0.1302]]]),
  tensor([0.2049, 0.1033])],
 [tensor([[[ 0.9082,  0.2878, -0.2668]],
  
          [[-1.0392, -

In [1]:
import os
import sys
root=os.path.abspath(r"D:\project_meta\NNproject\NNI")
print(root)
sys.path.append(root)
os.environ["TORCH_HOME"]=r"E:\Data\torch-model"
from project.train.operation import *
from torch.utils.data import *
import torch.nn as nn
import torch
from typing import Any
import os
import sys
root=os.path.abspath(r"D:\project_meta\NNproject\NNI")
print(root)
sys.path.append(root)
os.environ["TORCH_HOME"]=r"E:\Data\torch-model"
class TestDataset(Dataset):
    def __init__(self,shape:list):
        self.TestData=torch.randn(shape)
        self.label=torch.randn([shape[0]])
    def __len__(self):
        return len(self.TestData)
    def __getitem__(self, index) -> Any:
        return self.TestData[index],self.label[index]
    
featureNum=3
from torch.utils.data import *
testdataset=TestDataset([100,featureNum])
dataloader=DataLoader(testdataset,batch_size=2)


net=nn.Linear(3,1)
batchData=next(iter(dataloader))
forwardBatch(net=net,batchData=batchData)

D:\project_meta\NNproject\NNI
D:\project_meta\NNproject\NNI


(tensor([ 2.0716, -0.1792]),
 tensor([[1.1825],
         [1.0865]], grad_fn=<AddmmBackward0>))

In [2]:
optimizer=torch.optim.Adam(net.parameters(),lr=0.001)
lossFunction=nn.L1Loss()
y,y_hat,loss=trainBatch(net,batchData,optimizer,lossFunction)

g:\install\anaconda\envs\nni\lib\site-packages\torch\nn\modules\loss.py:101: UserWarning: Using a target size (torch.Size([2])) that is different to the input size (torch.Size([2, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.l1_loss(input, target, reduction=self.reduction)


In [13]:
loss.item()

0.34423354268074036

In [14]:
epochLoss=torch.tensor([])
epochLoss=torch.concat([epochLoss,torch.tensor([loss.item()])],dim=0)

In [3]:
evalOneEpoch(net,dataloader)

(tensor([ 2.0716e+00, -1.7921e-01, -1.7834e+00,  3.7834e-01,  6.7764e-01,
          9.6100e-02, -8.8062e-01, -4.8040e-01, -4.4534e-01, -8.3358e-01,
         -1.2237e-01, -1.6676e-01, -2.9686e-01, -7.6496e-01, -5.5224e-01,
          1.7918e+00,  3.6348e-01, -6.5663e-01, -1.4359e-01,  5.0950e-01,
         -6.4507e-01, -1.1251e+00,  1.7320e+00,  2.0487e-01,  3.0457e-03,
          7.7596e-01,  2.0037e-01,  7.4924e-01, -5.6603e-02,  9.6885e-01,
          7.7617e-01,  1.9924e-01, -8.8615e-01,  1.4182e+00, -6.7848e-01,
         -7.6258e-01, -3.3255e+00, -8.8864e-01,  3.8632e-01,  4.6204e-01,
         -7.5691e-01, -3.9685e-01,  4.6187e-01,  4.6527e-01, -8.7046e-01,
         -1.0716e+00,  2.2237e-02,  1.8187e-01, -1.7897e+00, -1.2175e+00,
          4.0050e-01,  1.1412e+00,  1.5698e+00, -9.5658e-01, -7.4454e-01,
         -4.3416e-01,  1.0574e+00,  1.5056e+00,  4.7902e-01, -1.7557e-01,
         -1.1451e+00,  7.2585e-01, -1.3359e-01, -3.0926e-01,  1.3283e-01,
          1.5146e-01, -1.3076e+00,  2.

In [3]:
trainOneEpoch(net,dataloader,optimizer,lossFunction)

tensor(1.4158, grad_fn=<MeanBackward0>)
tensor(0.9615, grad_fn=<MeanBackward0>)
tensor(0.6554, grad_fn=<MeanBackward0>)
tensor(0.7426, grad_fn=<MeanBackward0>)
tensor(1.3452, grad_fn=<MeanBackward0>)
tensor(0.8609, grad_fn=<MeanBackward0>)
tensor(0.8976, grad_fn=<MeanBackward0>)
tensor(0.8243, grad_fn=<MeanBackward0>)
tensor(0.5819, grad_fn=<MeanBackward0>)
tensor(0.9856, grad_fn=<MeanBackward0>)
tensor(1.1887, grad_fn=<MeanBackward0>)
tensor(1.2180, grad_fn=<MeanBackward0>)
tensor(0.5890, grad_fn=<MeanBackward0>)
tensor(0.8031, grad_fn=<MeanBackward0>)
tensor(0.8416, grad_fn=<MeanBackward0>)
tensor(0.4595, grad_fn=<MeanBackward0>)
tensor(0.9538, grad_fn=<MeanBackward0>)
tensor(1.1380, grad_fn=<MeanBackward0>)
tensor(0.5138, grad_fn=<MeanBackward0>)
tensor(0.9918, grad_fn=<MeanBackward0>)
tensor(0.4034, grad_fn=<MeanBackward0>)
tensor(2.3305, grad_fn=<MeanBackward0>)
tensor(1.0271, grad_fn=<MeanBackward0>)
tensor(1.4185, grad_fn=<MeanBackward0>)
tensor(1.7564, grad_fn=<MeanBackward0>)


{'epochY': tensor([ 0.6712,  2.3857,  0.7127, -1.0651, -1.1407,  0.1701,  0.8657,  0.0117,
         -0.0870,  2.1618,  0.9958, -0.7260,  0.4007, -0.4403,  0.7307,  0.2917,
          0.4259, -0.7379, -0.9820,  0.9892,  1.5229, -0.8545,  0.0983,  1.1406,
          0.9187,  1.2290, -0.5788, -1.5400,  1.1424, -0.5408,  0.4703,  0.9244,
          0.9605, -0.7266,  0.4614, -1.3394,  0.3943, -0.6145, -0.3748,  1.1281,
         -0.3883, -1.0440, -1.1175, -1.9388, -0.8537,  0.4723,  1.8873,  1.5299,
         -0.6787, -1.6343, -0.2545,  1.7904, -0.4338, -1.1827,  0.8505, -0.7089,
          1.6991,  1.5270, -0.1003,  0.9342, -1.0106,  1.0177, -1.1067,  1.1425,
         -0.6353,  0.2234,  0.6294, -0.6817, -0.5674,  1.5285, -0.6985,  0.0148,
         -0.4988,  1.6402, -0.0156,  1.9922, -0.4487,  0.4330, -1.1302,  1.1548,
          0.2015, -0.5014, -0.0995, -0.6425, -1.6156, -0.8307, -0.2232,  0.3382,
         -0.7789,  1.1122,  1.2095, -0.8039, -1.2079, -0.8095,  0.0850, -0.2426,
          0.3785, 

In [21]:
a=torch.tensor([])
b=torch.tensor([1,2])
c=torch.concat([a,b],dim=0)

In [2]:
import os
import sys
root=os.path.abspath(os.path.join(r"D:\project_meta\NNproject\NNI\notebook\NNITest_0231104.ipynb","../.."))
print(root)
sys.path.append(root)
os.environ["TORCH_HOME"]=r"E:\Data\torch-model"
from project.dataset.SelfDataset import TableControlFullLoadDataset
from project.dataprocess.FolderTree import *
import pandas as pd

datasetDict=getDataPath(r"D:\dataset\driver_dataset\DROZY\DROZY")
outputDict=getOutPath(r"D:\project_meta\NNproject\NNI\output")


D:\project_meta\NNproject\NNI


In [35]:
class LEVELDataset(TableControlFullLoadDataset):
    def __getitem__(self, index):
        superreturn = super().__getitem__(index)
        return torch.tensor(superreturn['data']).to(torch.float32),torch.tensor(superreturn['LEVEL']).long()
infoTable=pd.read_csv(outputDict['info_file'])
dataset=LEVELDataset(infoTable,data_root=r"D:\dataset\driver_dataset\DROZY\DROZY",output_root=r"D:\project_meta\NNproject\NNI\output")
from torch.utils.data import *
dataloader=DataLoader(dataset,3)

In [36]:
from project.model.CNN1D import simple_cnn1d
cnn=simple_cnn1d(input_channels=5,num_classes=4,list_down=[16,32,64,64,64])
from torchsummary import summary
summary(cnn,(5,3*2560),batch_size=3,device="cpu")

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Conv1d-1              [3, 16, 7680]             576
       BatchNorm1d-2              [3, 16, 7680]              32
              ReLU-3              [3, 16, 7680]               0
         MaxPool1d-4              [3, 16, 3839]               0
            Conv1d-5              [3, 32, 1920]           1,568
       BatchNorm1d-6              [3, 32, 1920]              64
              ReLU-7              [3, 32, 1920]               0
            Conv1d-8               [3, 64, 960]           6,208
       BatchNorm1d-9               [3, 64, 960]             128
             ReLU-10               [3, 64, 960]               0
           Conv1d-11               [3, 64, 480]          12,352
      BatchNorm1d-12               [3, 64, 480]             128
             ReLU-13               [3, 64, 480]               0
           Conv1d-14               [3, 

In [37]:
from project.train.operation import *
from torch import nn
optimizer=torch.optim.Adam(cnn.parameters(),lr=0.001)
lossFunction=nn.CrossEntropyLoss()

forwardBatch(cnn,next(iter(dataloader)))

D:\project_meta\NNproject\NNI\project\dataset\SelfDataset.py:211: RuntimeWarning: This filename (D:\project_meta\NNproject\NNI\output\psg_uniformfilted\1-1-EEG.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  self.psg_file = mne.io.read_raw_fif(os.path.join(self.out_path_dict["uniformfilted_folder"], file_name),verbose=False)


(tensor([1, 1, 1]),
 tensor([[ 0.1976, -0.4182,  0.2427,  0.3306],
         [ 0.1235, -0.4830,  0.3132,  0.3182],
         [ 0.1396, -0.3852,  0.1962,  0.3259]], grad_fn=<AddmmBackward0>))

In [38]:
trainEpochs(1,cnn,dataloader,dataloader,optimizer,lossFunction)

D:\project_meta\NNproject\NNI\project\dataset\SelfDataset.py:211: RuntimeWarning: This filename (D:\project_meta\NNproject\NNI\output\psg_uniformfilted\1-2-EEG.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  self.psg_file = mne.io.read_raw_fif(os.path.join(self.out_path_dict["uniformfilted_folder"], file_name),verbose=False)
D:\project_meta\NNproject\NNI\project\dataset\SelfDataset.py:211: RuntimeWarning: This filename (D:\project_meta\NNproject\NNI\output\psg_uniformfilted\1-3-EEG.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  self.psg_file = mne.io.read_raw_fif(os.path.join(self.out_path_dict["uniformfilted_folder"], 