In [3]:
import mne
import os
edfFile=mne.io.read_raw_fif(r'D:\project_meta\NNproject\NNI\output\psg_filted\1-1-EEG.fif')

Opening raw data file D:\project_meta\NNproject\NNI\output\psg_filted\1-1-EEG.fif...
Isotrak not found
    Range : 0 ... 307199 =      0.000 ...   599.998 secs
Ready.


In [4]:
import torch
N_FFT=15*512
HOP_LENGTH=15*512
startIndex=torch.range(0,((len(edfFile)-N_FFT)//HOP_LENGTH))*HOP_LENGTH
endIndex=startIndex+N_FFT

C:\Users\Frantic\AppData\Local\Temp\ipykernel_27988\3845600040.py:4: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  startIndex=torch.range(0,((len(edfFile)-N_FFT)//HOP_LENGTH))*HOP_LENGTH


In [17]:
import mne
import torch
N_FFT=15*512
ID_LEVEL_EEGECG,Type='1-1-EEG.fif'.split('.')
ID,LEVEL,EEGECG=ID_LEVEL_EEGECG.split('-')
edfFile=mne.io.read_raw_fif(r'D:\project_meta\NNproject\NNI\output\psg_filted\1-1-EEG.fif')
print((len(edfFile)))
startIndex=(torch.range(0,((len(edfFile)-N_FFT)//N_FFT))*N_FFT)
startTime=startIndex/512
print(startIndex)
print(ID)
print(type(ID))
ID=(torch.ones_like(startTime))*int(ID)
print(ID)

Opening raw data file D:\project_meta\NNproject\NNI\output\psg_filted\1-1-EEG.fif...
Isotrak not found
    Range : 0 ... 307199 =      0.000 ...   599.998 secs
Ready.
307200
tensor([     0.,   7680.,  15360.,  23040.,  30720.,  38400.,  46080.,  53760.,
         61440.,  69120.,  76800.,  84480.,  92160.,  99840., 107520., 115200.,
        122880., 130560., 138240., 145920., 153600., 161280., 168960., 176640.,
        184320., 192000., 199680., 207360., 215040., 222720., 230400., 238080.,
        245760., 253440., 261120., 268800., 276480., 284160., 291840., 299520.])
1
<class 'str'>
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.])


C:\Users\Frantic\AppData\Local\Temp\ipykernel_29336\1109144022.py:8: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  startIndex=(torch.range(0,((len(edfFile)-N_FFT)//N_FFT))*N_FFT)


In [8]:
idxs=torch.stack((startIndex,endIndex),dim=1).int()

In [9]:
idxs

tensor([[     0,   7680],
        [  7680,  15360],
        [ 15360,  23040],
        [ 23040,  30720],
        [ 30720,  38400],
        [ 38400,  46080],
        [ 46080,  53760],
        [ 53760,  61440],
        [ 61440,  69120],
        [ 69120,  76800],
        [ 76800,  84480],
        [ 84480,  92160],
        [ 92160,  99840],
        [ 99840, 107520],
        [107520, 115200],
        [115200, 122880],
        [122880, 130560],
        [130560, 138240],
        [138240, 145920],
        [145920, 153600],
        [153600, 161280],
        [161280, 168960],
        [168960, 176640],
        [176640, 184320],
        [184320, 192000],
        [192000, 199680],
        [199680, 207360],
        [207360, 215040],
        [215040, 222720],
        [222720, 230400],
        [230400, 238080],
        [238080, 245760],
        [245760, 253440],
        [253440, 261120],
        [261120, 268800],
        [268800, 276480],
        [276480, 284160],
        [284160, 291840],
        [291

In [6]:
startTime=startIndex/512
startTime

tensor([  0.,  15.,  30.,  45.,  60.,  75.,  90., 105., 120., 135., 150., 165.,
        180., 195., 210., 225., 240., 255., 270., 285., 300., 315., 330., 345.,
        360., 375., 390., 405., 420., 435., 450., 465., 480., 495., 510., 525.,
        540., 555., 570., 585.])

In [13]:
startIndex.int()

tensor([     0,   7680,  15360,  23040,  30720,  38400,  46080,  53760,  61440,
         69120,  76800,  84480,  92160,  99840, 107520, 115200, 122880, 130560,
        138240, 145920, 153600, 161280, 168960, 176640, 184320, 192000, 199680,
        207360, 215040, 222720, 230400, 238080, 245760, 253440, 261120, 268800,
        276480, 284160, 291840, 299520], dtype=torch.int32)

In [1]:
import os
import sys
root=os.path.abspath(os.path.join(r"D:\project_meta\NNproject\NNI\notebook\NNITest_0231104.ipynb","../.."))
print(root)
sys.path.append(root)
os.environ["TORCH_HOME"]=r"E:\Data\torch-model"
import warnings  
warnings.filterwarnings("ignore", category=RuntimeWarning, module="mne")
from project.dataprocess.DatasetProcess import MakeNonCrossTable
from project.dataprocess.FolderTree import getDataPath,getOutPath

data_root=r'D:\dataset\driver_dataset\DROZY\DROZY'
dataDict=getDataPath(data_root)

D:\project_meta\NNproject\NNI


In [7]:
import pandas as pd
df=pd.DataFrame()
data = {'name': ['John', 'Smith', 'Adam'],
        'age': [23, 45, 56],
        'gender': ['M', 'M', 'M']}

tempdf = pd.DataFrame(data)

df=pd.concat([df,tempdf])
df

name  age gender
0   John   23      M
1  Smith   45      M
2   Adam   56      M

In [10]:
df=pd.concat([df,tempdf],ignore_index=True)
df

name  age gender
0    John   23      M
1   Smith   45      M
2    Adam   56      M
3    John   23      M
4   Smith   45      M
5    Adam   56      M
6    John   23      M
7   Smith   45      M
8    Adam   56      M
9    John   23      M
10  Smith   45      M
11   Adam   56      M

In [29]:
import os
import sys
import mne
import torch
import os
import sys
import pandas as pd
mne.set_log_level('ERROR') 
root=os.path.abspath(os.path.join(r"D:\project_meta\NNproject\NNI\notebook\NNITest_0231104.ipynb","../.."))
print(root)
sys.path.append(root)
os.environ["TORCH_HOME"]=r"E:\Data\torch-model"
import warnings  
warnings.filterwarnings("ignore", category=RuntimeWarning, module="mne")
def MakeNonCrossTable(psg_folder,kss_file_path,N_FFT=15*512):
    '''
    获取实验数据：实验人员ID,实验次序，每次反应测试的间隔起始时间、间隔终结时间和反应时长
    输出pandas.Dataframe,columns=["ID","LEVEL","KSS","START", "END","SPEED"]
    '''
    
    date_format = '%Y-%m-%d_%H.%M.%S.%f'
    df=pd.DataFrame(columns=["ID","LEVEL","KSS","START", "END"])
    edfFilenameList=os.listdir(psg_folder)
    for edfFilename in edfFilenameList:
        dict={}
        ID_LEVE,Type=edfFilename.split('.')
        ID,LEVEL=ID_LEVE.split('-')
        try:
            KSS_table=pd.read_csv(kss_file_path,sep=" ",header=None)
            KSS=KSS_table.iloc[int(ID)-1][int(LEVEL)-1]
        except ValueError:
            continue
        edfFile=mne.io.read_raw_edf(os.path.join(psg_folder,edfFilename),verbose=False)      
        
        startIndex=torch.range(0,((len(edfFile)-N_FFT)//N_FFT))*N_FFT
        startTime=startIndex/512
        endIndex=startIndex+N_FFT
        endTime=endIndex/512
        ID=torch.ones_like(startTime)*int(ID)
        LEVEL=torch.ones_like(startTime)*int(LEVEL)
        KSS=torch.ones_like(startTime)*int(KSS)
        dict['ID']=ID
        dict['LEVEL']=LEVEL
        dict["KSS"]=KSS
        dict["START"]=startTime
        dict["END"]=endTime
        tempdf=pd.DataFrame(dict)
        print(tempdf.shape)
        df=pd.concat([df,tempdf],ignore_index=True)
    print(df)
    return df

D:\project_meta\NNproject\NNI


In [31]:
from project.dataprocess.FolderTree import getDataPath,getOutPath
data_root=r'D:\dataset\driver_dataset\DROZY\DROZY'
dataDict=getDataPath(data_root)
a=MakeNonCrossTable(dataDict['psg_folder'],dataDict['kss_file']).to_csv(r'D:\project_meta\NNproject\NNI\output\noncross.csv')

(40, 5)
(40, 5)
(40, 5)
(40, 5)
(40, 5)
(40, 5)
(40, 5)
(40, 5)
(40, 5)
(40, 5)
(40, 5)
(40, 5)
(40, 5)
(40, 5)
(40, 5)
(40, 5)
(40, 5)
(40, 5)
(40, 5)
(40, 5)
(40, 5)
(40, 5)
(40, 5)
(40, 5)
(40, 5)
(40, 5)
(40, 5)
(40, 5)
(40, 5)
(40, 5)
(40, 5)
(40, 5)
(40, 5)
(40, 5)
(40, 5)
(40, 5)
       ID  LEVEL  KSS  START    END
0     1.0    1.0  3.0    0.0   15.0
1     1.0    1.0  3.0   15.0   30.0
2     1.0    1.0  3.0   30.0   45.0
3     1.0    1.0  3.0   45.0   60.0
4     1.0    1.0  3.0   60.0   75.0
...   ...    ...  ...    ...    ...
1435  9.0    3.0  8.0  525.0  540.0
1436  9.0    3.0  8.0  540.0  555.0
1437  9.0    3.0  8.0  555.0  570.0
1438  9.0    3.0  8.0  570.0  585.0
1439  9.0    3.0  8.0  585.0  600.0

[1440 rows x 5 columns]


C:\Users\Frantic\AppData\Local\Temp\ipykernel_29504\3018131614.py:35: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  startIndex=torch.range(0,((len(edfFile)-N_FFT)//N_FFT))*N_FFT
C:\Users\Frantic\AppData\Local\Temp\ipykernel_29504\3018131614.py:35: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  startIndex=torch.range(0,((len(edfFile)-N_FFT)//N_FFT))*N_FFT
C:\Users\Frantic\AppData\Local\Temp\ipykernel_29504\3018131614.py:35: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  startIndex=torch.range(0,((

In [32]:
a

ID  LEVEL  KSS  START    END
0     1.0    1.0  3.0    0.0   15.0
1     1.0    1.0  3.0   15.0   30.0
2     1.0    1.0  3.0   30.0   45.0
3     1.0    1.0  3.0   45.0   60.0
4     1.0    1.0  3.0   60.0   75.0
...   ...    ...  ...    ...    ...
1435  9.0    3.0  8.0  525.0  540.0
1436  9.0    3.0  8.0  540.0  555.0
1437  9.0    3.0  8.0  555.0  570.0
1438  9.0    3.0  8.0  570.0  585.0
1439  9.0    3.0  8.0  585.0  600.0

[1440 rows x 5 columns]